name: task_manager_app
description: "Task Manager App"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.2+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  build_runner: ^2.4.11
  cached_network_image: ^3.3.1
  carousel_slider: ^4.2.1
  convex_bottom_bar: ^3.2.0
  cupertino_icons: ^1.0.6
  device_preview: ^1.2.0
  dio: ^5.4.3+1
  equatable: ^2.0.5
  firebase_auth: ^5.1.0
  firebase_core: ^3.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0
  flutter_screenutil: ^5.9.3
  flutter_secure_storage: ^4.2.1
  flutter_svg: ^2.0.10+1
  get: ^4.6.6
  get_it: ^7.7.0
  google_sign_in: ^6.2.1
  iconsax: ^0.0.8
  intl: ^0.19.0

  logger: ^2.3.0
  path: ^1.9.0
  pretty_dio_logger: ^1.3.1
  smooth_page_indicator: ^1.1.0

dev_dependencies:

  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/svgs/

  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Black.ttf
          weight: 900
        - asset: assets/fonts/Lato-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: assets/fonts/Lato-Bold.ttf
          weight: 700
        - asset: assets/fonts/Lato-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Lato-Italic.ttf
          style: italic
        - asset: assets/fonts/Lato-Light.ttf
          weight: 300
        - asset: assets/fonts/Lato-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Lato-Regular.ttf
        - asset: assets/fonts/Lato-Thin.ttf
          weight: 100
        - asset: assets/fonts/Lato-ThinItalic.ttf
          weight: 100
          style: italic
