// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBP47orXfBJ0_PVvd3AX91GR4PVeMWzoYU',
    appId: '1:158766218795:android:af5cfcb13290360f27f46e',
    messagingSenderId: '158766218795',
    projectId: 'cool-maids-task-manager',
    storageBucket: 'cool-maids-task-manager.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrlbNB2_R27aW8GUg328KvNsVUZh1Yy9k',
    appId: '1:158766218795:ios:94bbcc37c59edbb227f46e',
    messagingSenderId: '158766218795',
    projectId: 'cool-maids-task-manager',
    storageBucket: 'cool-maids-task-manager.appspot.com',
    iosBundleId: 'com.example.taskManagerApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjeMS2rB4eWmND3zhBEFd5BeL__Y8Dd7w',
    appId: '1:158766218795:web:fb60ae36721681ba27f46e',
    messagingSenderId: '158766218795',
    projectId: 'cool-maids-task-manager',
    authDomain: 'cool-maids-task-manager.firebaseapp.com',
    storageBucket: 'cool-maids-task-manager.appspot.com',
  );

}