name: Android Fastlane App Distribution Workflow

on:
  push:
    branches:
      - main

jobs:
  distribution_to_firebase:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout My Repository
        uses: actions/checkout@v2

      - name: Setup JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install Ruby Dependencies
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3.3'
          bundler-cache: true
          working-directory: android

      - name: Get Latest Commit Message
        id: get_commit_message
        run: |
          git log -1 --pretty=%B > commit_message.txt

      - name: Flutter Build Android App And Upload To Firebase
        env:
          FIREBASE_CLI_TOKEN: ${{ secrets.FIREBASE_CLI_TOKEN }}
        run: |
          RELEASE_NOTES=$(<commit_message.txt) bundle exec fastlane android firebase_distribution release_notes:"$RELEASE_NOTES"
        working-directory: android
